"""empty message

Revision ID: 866398209fef
Revises: b5886045c1cf
Create Date: 2020-05-28 07:27:42.002402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '866398209fef'
down_revision = 'b5886045c1cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_venue', sa.Boolean(), nullable=False))
    op.drop_column('artist', 'seeking_talent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_talent', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('artist', 'seeking_venue')
    # ### end Alembic commands ###
